name: deploy render
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger para render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}